//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirsoftReservationsAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int Id { get; set; }
        public Nullable<int> ReservationBy { get; set; }
        public Nullable<int> NumberOfGuns { get; set; }
        public Nullable<int> NumberOfMagazines { get; set; }
        public Nullable<int> NumberOfPeople { get; set; }
        public Nullable<int> GameId { get; set; }
    }
}
